### ISSUE TITLE
On missing string, non-default language is used

### ISSUE THREAD

**Issue by paalex** [stefalda/ReactNativeLocalization#66]
I'm changing the app language during runtime (see screenshot).
Once in a certain language a string is **missing** the default language should be used ('en' in my case, which is the first localization in the Strings.js file).

Instead, the 'last used' language is being displayed..

See attached screenshots. In both the Italian language is currently selected but for one screenshot the Chinese language was used prior to the Italian.

After restarting the app it works as intended (for missing italian strings the 'en' strings are being used)

When app loads:
![screenshot 2017-03-07 13 29 13](https://cloud.githubusercontent.com/assets/11162015/23664291/da4b039c-035d-11e7-8791-38091c6b0779.png)

After changing to Chinese and changing back to Italian
![screenshot 2017-03-07 13 28 52](https://cloud.githubusercontent.com/assets/11162015/23664290/da47888e-035d-11e7-9de9-e698366b6c4e.png)

**Comment by paalex** [comment]
Commited a fix that checks whether the current string equals to the default language string:
https://github.com/stefalda/ReactNativeLocalization/pull/67

**Comment by stefalda** [comment]
@paalex your commit breaks when strings are structured as object...
we have to find another way to achieve the result... I've not been able to reproduce the behaviour...

**Comment by paalex** [comment]
@stefalda the issue occurs because, once you force a language, the strings from the new language override only the old ones, but for non-existing keys nothing overrides the old values.
`_fallbackValues` checks only whether there is a key `(!strings[key]),` since there IS an existing key-value from the previous language, this key-value is not overridden.
Also, in case a string exists in the old language but is missing in the new one (and missing in the default language), the old string would be used.

I think best practice would be to reset all the strings on language change, this way no chance there would be anything left from the previous language (and `_fallbackValues`  would work properly.
But I wasn't yet able to figure out how to do that since the strings are stored in `this[key]`

**Comment by stefalda** [comment]
Hi @paalex I've fixed the problem and released a new version on npm...

**Comment by paalex** [comment]
@stefalda Thanks!

it's better now.
there is still an issue when a string is missing in the selected language and the default language. 
a string from the previous language is then used.
it is inconsistent behavior because once you restart the app this string becomes empty (doesn't exist in the current and the default language)

**Comment by stefalda** [comment]
The main object properties are overwritten but only if they exists in language set (or at least in the default language). So there's no fix for this, unless start keeping an inventory of all the  properties added when the language is set
